/*  */
package fr.inria.diverse.mobileprivacyprofilerserver.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collection;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import fr.inria.diverse.mobileprivacyprofilerserver.datamodel.associations.DetectedWifi_AccessPoint;
// Start of user code additional import for BatteryUsage
// End of user code

/** 
  * https://developer.android.com/training/monitoring-device-state/battery-monitoring.html 
  */ 
@DatabaseTable(tableName = "batteryUsage")
public class BatteryUsage {

	public static Log log = LogFactory.getLog(BatteryUsage.class);

	public static final String XML_BATTERYUSAGE = "BATTERYUSAGE";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_DATE = "date";
	public static final String XML_ATT_LEVEL = "level";
	public static final String XML_ATT_ISPUGGED = "isPugged";
	public static final String XML_ATT_PLUGTYPE = "plugType";
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	protected MobilePrivacyProfilerDBHelper _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */
	

	@DatabaseField
	protected java.util.Date date;

	@DatabaseField
	protected int level;

	@DatabaseField
	protected int isPugged;

	/** Possible type :
"BATTERY_PLUGGED_USB",
"BATTERY_PLUGGED_AC",
"BATTERY_PLUGGED_WIRELESS",
 "BATTERY_NOT_PLUGGED" */ 
	@DatabaseField
	protected String plugType;
	

	// Start of user code BatteryUsage additional user properties

	// End of user code
	
	public BatteryUsage() {} // needed by ormlite
	public BatteryUsage(java.util.Date date, int level, int isPugged, String plugType) {
		super();
		this.date = date;
		this.level = level;
		this.isPugged = isPugged;
		this.plugType = plugType;
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}

	public MobilePrivacyProfilerDBHelper getContextDB(){
		return _contextDB;
	}
	public void setContextDB(MobilePrivacyProfilerDBHelper contextDB){
		this._contextDB = contextDB;
	}

	public java.util.Date getDate() {
		return this.date;
	}
	public void setDate(java.util.Date date) {
		this.date = date;
	}
	public int getLevel() {
		return this.level;
	}
	public void setLevel(int level) {
		this.level = level;
	}
	public int getIsPugged() {
		return this.isPugged;
	}
	public void setIsPugged(int isPugged) {
		this.isPugged = isPugged;
	}
	public String getPlugType() {
		return this.plugType;
	}
	public void setPlugType(String plugType) {
		this.plugType = plugType;
	}




	public String toXML(String indent, MobilePrivacyProfilerDBHelper contextDB){
		StringBuilder sb = new StringBuilder();
		sb.append(indent+"<");
    	sb.append(XML_BATTERYUSAGE);
		sb.append(" "+XML_ATT_ID+"=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_DATE);
    	sb.append("=\"");
		sb.append(this.date);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_LEVEL);
    	sb.append("=\"");
		sb.append(this.level);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_ISPUGGED);
    	sb.append("=\"");
		sb.append(this.isPugged);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_PLUGTYPE);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.plugType));
    	sb.append("\" ");
    	sb.append(">");


		// TODO deal with other case

		sb.append("</"+XML_BATTERYUSAGE+">");
		return sb.toString();
	}
}
