/*  */
package fr.inria.diverse.mobileprivacyprofilerserver.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collection;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import fr.inria.diverse.mobileprivacyprofilerserver.datamodel.associations.DetectedWifi_AccessPoint;
// Start of user code additional import for BluetoothDevice
// End of user code

/** 
  *  
  */ 
@DatabaseTable(tableName = "bluetoothDevice")
public class BluetoothDevice {

	public static Log log = LogFactory.getLog(BluetoothDevice.class);

	public static final String XML_BLUETOOTHDEVICE = "BLUETOOTHDEVICE";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_MAC = "mac";
	public static final String XML_ATT_NAME = "name";
	public static final String XML_ATT_TYPE = "type";
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	protected MobilePrivacyProfilerDBHelper _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */
	

	@DatabaseField
	protected String mac;

	@DatabaseField
	protected String name;

	/** https://developer.android.com/reference/android/bluetooth/BluetoothClass.Device.html */ 
	@DatabaseField
	protected int type;
	

	// Start of user code BluetoothDevice additional user properties
	// End of user code
	
	public BluetoothDevice() {} // needed by ormlite
	public BluetoothDevice(String mac, String name, int type) {
		super();
		this.mac = mac;
		this.name = name;
		this.type = type;
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}

	public MobilePrivacyProfilerDBHelper getContextDB(){
		return _contextDB;
	}
	public void setContextDB(MobilePrivacyProfilerDBHelper contextDB){
		this._contextDB = contextDB;
	}

	public String getMac() {
		return this.mac;
	}
	public void setMac(String mac) {
		this.mac = mac;
	}
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getType() {
		return this.type;
	}
	public void setType(int type) {
		this.type = type;
	}




	public String toXML(String indent, MobilePrivacyProfilerDBHelper contextDB){
		StringBuilder sb = new StringBuilder();
		sb.append(indent+"<");
    	sb.append(XML_BLUETOOTHDEVICE);
		sb.append(" "+XML_ATT_ID+"=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_MAC);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.mac));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_NAME);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.name));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_TYPE);
    	sb.append("=\"");
		sb.append(this.type);
    	sb.append("\" ");
    	sb.append(">");


		// TODO deal with other case

		sb.append("</"+XML_BLUETOOTHDEVICE+">");
		return sb.toString();
	}
}
