/*  */
package fr.inria.diverse.mobileprivacyprofilerserver.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collection;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import fr.inria.diverse.mobileprivacyprofilerserver.datamodel.associations.DetectedWifi_AccessPoint;
// Start of user code additional import for CalendarEvent
// End of user code

/** 
  *  
  */ 
@DatabaseTable(tableName = "calendarEvent")
public class CalendarEvent {

	public static Log log = LogFactory.getLog(CalendarEvent.class);

	public static final String XML_CALENDAREVENT = "CALENDAREVENT";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_EVENTLABEL = "eventLabel";
	public static final String XML_ATT_STARTDATE = "startDate";
	public static final String XML_ATT_ENDDATE = "endDate";
	public static final String XML_ATT_PLACE = "place";
	public static final String XML_ATT_PARTICIPANTS = "participants";
	public static final String XML_ATT_EVENTID = "eventId";
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	protected MobilePrivacyProfilerDBHelper _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */
	

	@DatabaseField
	protected String eventLabel;

	@DatabaseField
	protected String startDate;

	@DatabaseField
	protected String endDate;

	/** place where the event is supposed to occur */ 
	@DatabaseField
	protected String place;

	/** list of participants (raw string for the moment) */ 
	@DatabaseField(dataType = com.j256.ormlite.field.DataType.LONG_STRING)
	protected String participants;

	@DatabaseField
	protected long eventId;
	

	// Start of user code CalendarEvent additional user properties
	// End of user code
	
	public CalendarEvent() {} // needed by ormlite
	public CalendarEvent(String eventLabel, String startDate, String endDate, String place, String participants, long eventId) {
		super();
		this.eventLabel = eventLabel;
		this.startDate = startDate;
		this.endDate = endDate;
		this.place = place;
		this.participants = participants;
		this.eventId = eventId;
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}

	public MobilePrivacyProfilerDBHelper getContextDB(){
		return _contextDB;
	}
	public void setContextDB(MobilePrivacyProfilerDBHelper contextDB){
		this._contextDB = contextDB;
	}

	public String getEventLabel() {
		return this.eventLabel;
	}
	public void setEventLabel(String eventLabel) {
		this.eventLabel = eventLabel;
	}
	public String getStartDate() {
		return this.startDate;
	}
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}
	public String getEndDate() {
		return this.endDate;
	}
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}
	public String getPlace() {
		return this.place;
	}
	public void setPlace(String place) {
		this.place = place;
	}
	public String getParticipants() {
		return this.participants;
	}
	public void setParticipants(String participants) {
		this.participants = participants;
	}
	public long getEventId() {
		return this.eventId;
	}
	public void setEventId(long eventId) {
		this.eventId = eventId;
	}




	public String toXML(String indent, MobilePrivacyProfilerDBHelper contextDB){
		StringBuilder sb = new StringBuilder();
		sb.append(indent+"<");
    	sb.append(XML_CALENDAREVENT);
		sb.append(" "+XML_ATT_ID+"=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_EVENTLABEL);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.eventLabel));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_STARTDATE);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.startDate));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_ENDDATE);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.endDate));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_PLACE);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.place));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_PARTICIPANTS);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.participants));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_EVENTID);
    	sb.append("=\"");
		sb.append(this.eventId);
    	sb.append("\" ");
    	sb.append(">");


		// TODO deal with other case

		sb.append("</"+XML_CALENDAREVENT+">");
		return sb.toString();
	}
}
