/*  */
package fr.inria.diverse.mobileprivacyprofilerserver.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collection;

import fr.inria.diverse.mobileprivacyprofilerserver.datamodel.MobilePrivacyProfilerDBHelper;
import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

// Start of user code additional import for ContactIM
// End of user code

/** 
  *  
  */ 
@DatabaseTable(tableName = "contactIM")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, 
                  property  = "_id",
				  scope = ContactIM.class)
public class ContactIM {

	public static Log log = LogFactory.getLog(ContactIM.class);

	public static final String XML_CONTACTIM = "CONTACTIM";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_PROTOCOLE = "protocole";
	public static final String XML_ATT_IMID = "imId";
	public static final String XML_ATT_USERID = "userId";
	public static final String XML_REF_CONTACT = "contact";
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	@JsonIgnore
	protected MobilePrivacyProfilerDBHelper _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */
	@JsonIgnore
	public boolean contact_mayNeedDBRefresh = true;
	

	@DatabaseField
	protected java.lang.String protocole;

	@DatabaseField
	protected java.lang.String imId;

	@DatabaseField
	protected java.lang.String userId;


	@DatabaseField(foreign = true) //, columnName = USER_ID_FIELD_NAME)
	// @JsonManagedReference(value="contact_contactim")
	protected Contact contact;

	// Start of user code ContactIM additional user properties
	// End of user code
	
	public ContactIM() {} // needed by ormlite
	public ContactIM(java.lang.String protocole, java.lang.String imId, java.lang.String userId) {
		super();
		this.protocole = protocole;
		this.imId = imId;
		this.userId = userId;
	}

	public int get_id() {
		return _id;
	}
	@JsonProperty
	public void set_id(int id) {
		this._id = id;
	}

	public int getId() {
		return _id;
	}
	@JsonProperty
	public void setId(int id) {
		this._id = id;
	}

	public MobilePrivacyProfilerDBHelper getContextDB(){
		return _contextDB;
	}
	@JsonIgnore
	public void setContextDB(MobilePrivacyProfilerDBHelper contextDB){
		this._contextDB = contextDB;
	}

	public java.lang.String getProtocole() {
		return this.protocole;
	}
	@JsonProperty
	public void setProtocole(java.lang.String protocole) {
		this.protocole = protocole;
	}
	public java.lang.String getImId() {
		return this.imId;
	}
	@JsonProperty
	public void setImId(java.lang.String imId) {
		this.imId = imId;
	}
	public java.lang.String getUserId() {
		return this.userId;
	}
	@JsonProperty
	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public Contact getContact() {
		try {
			if(contact_mayNeedDBRefresh && _contextDB != null){
				_contextDB.contactDao.refresh(this.contact);
				contact_mayNeedDBRefresh = false;
			}
		} catch (SQLException e) {
			log.error(e.getMessage(),e);
		}
		if(_contextDB==null && this.contact == null){
			log.warn("ContactIM may not be properly refreshed from DB (_id="+_id+")");
		}
		return this.contact;
	}
	@JsonProperty
	public void setContact(Contact contact) {
		this.contact = contact;
	}			



	public String toXML(String indent, MobilePrivacyProfilerDBHelper contextDB){
		StringBuilder sb = new StringBuilder();
		sb.append(indent+"<");
    	sb.append(XML_CONTACTIM);
		sb.append(" "+XML_ATT_ID+"=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_PROTOCOLE);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.protocole));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_IMID);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.imId));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_USERID);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.userId));
    	sb.append("\" ");
    	sb.append(">");


		// TODO deal with other case

		sb.append("</"+XML_CONTACTIM+">");
		return sb.toString();
	}
}
