/*  */
package fr.inria.diverse.mobileprivacyprofilerserver.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collection;

import fr.inria.diverse.mobileprivacyprofilerserver.datamodel.MobilePrivacyProfilerDBHelper;
import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

// Start of user code additional import for ContactOrganisation
// End of user code

/** 
  *  
  */ 
@DatabaseTable(tableName = "contactOrganisation")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, 
                  property  = "_id",
				  scope = ContactOrganisation.class)
public class ContactOrganisation implements DbClass{

	public static Log log = LogFactory.getLog(ContactOrganisation.class);

	public static final String XML_CONTACTORGANISATION = "CONTACTORGANISATION";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_COMPANY = "company";
	public static final String XML_ATT_TITLE = "title";
	public static final String XML_ATT_USERID = "userId";
	public static final String XML_REF_REFERENCEDCONTACT = "referencedContact";
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	@JsonIgnore
	protected MobilePrivacyProfilerDBHelper _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */
	@JsonIgnore
	public boolean referencedContact_mayNeedDBRefresh = true;
	

	@DatabaseField
	protected java.lang.String company;

	@DatabaseField
	protected java.lang.String title;

	@DatabaseField
	protected java.lang.String userId;


	@DatabaseField(foreign = true) //, columnName = USER_ID_FIELD_NAME)
	// @JsonManagedReference(value="contact_contactorganisation")
	protected Contact referencedContact;

	// Start of user code ContactOrganisation additional user properties
	// End of user code
	
	public ContactOrganisation() {} // needed by ormlite
	public ContactOrganisation(java.lang.String company, java.lang.String title, java.lang.String userId) {
		super();
		this.company = company;
		this.title = title;
		this.userId = userId;
	}

	public int get_id() {
		return _id;
	}
	@JsonProperty
	public void set_id(int id) {
		this._id = id;
	}

	public int getId() {
		return _id;
	}
	@JsonProperty
	public void setId(int id) {
		this._id = id;
	}

	public MobilePrivacyProfilerDBHelper getContextDB(){
		return _contextDB;
	}
	@JsonIgnore
	public void setContextDB(MobilePrivacyProfilerDBHelper contextDB){
		this._contextDB = contextDB;
	}

	public java.lang.String getCompany() {
		return this.company;
	}
	@JsonProperty
	public void setCompany(java.lang.String company) {
		this.company = company;
	}
	public java.lang.String getTitle() {
		return this.title;
	}
	@JsonProperty
	public void setTitle(java.lang.String title) {
		this.title = title;
	}
	public java.lang.String getUserId() {
		return this.userId;
	}
	@JsonProperty
	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public Contact getReferencedContact() {
		try {
			if(referencedContact_mayNeedDBRefresh && _contextDB != null){
				_contextDB.contactDao.refresh(this.referencedContact);
				referencedContact_mayNeedDBRefresh = false;
			}
		} catch (SQLException e) {
			log.error(e.getMessage(),e);
		}
		if(_contextDB==null && this.referencedContact == null){
			log.warn("ContactOrganisation may not be properly refreshed from DB (_id="+_id+")");
		}
		return this.referencedContact;
	}
	@JsonProperty
	public void setReferencedContact(Contact referencedContact) {
		this.referencedContact = referencedContact;
	}			



	public String toXML(String indent, MobilePrivacyProfilerDBHelper contextDB){
		StringBuilder sb = new StringBuilder();
		sb.append(indent+"<");
    	sb.append(XML_CONTACTORGANISATION);
		sb.append(" "+XML_ATT_ID+"=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_COMPANY);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.company));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_TITLE);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.title));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_USERID);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.userId));
    	sb.append("\" ");
    	sb.append(">");


		// TODO deal with other case

		sb.append("</"+XML_CONTACTORGANISATION+">");
		return sb.toString();
	}
}
