/*  */
package fr.inria.diverse.mobileprivacyprofilerserver.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collection;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

// Start of user code additional import for Geolocation
// End of user code

/** 
  *  
  */ 
@DatabaseTable(tableName = "geolocation")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, 
                  property  = "_id",
				  scope = Geolocation.class)
public class Geolocation {

	public static Log log = LogFactory.getLog(Geolocation.class);

	public static final String XML_GEOLOCATION = "GEOLOCATION";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_DATE = "date";
	public static final String XML_ATT_POSITION = "position";
	public static final String XML_ATT_PRECISION = "precision";
	public static final String XML_ATT_ALTITUDE = "altitude";
	public static final String XML_ATT_USERID = "userId";
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	@JsonIgnore
	protected MobilePrivacyProfilerDBHelper _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */
	

	@DatabaseField
	protected java.lang.String date;

	@DatabaseField
	protected java.lang.String position;

	/** precision in centimeter */ 
	@DatabaseField
	protected int precision;

	/** altitude in meter */ 
	@DatabaseField
	protected int altitude;

	@DatabaseField
	protected java.lang.String userId;


	// Start of user code Geolocation additional user properties
	// End of user code
	
	public Geolocation() {} // needed by ormlite
	public Geolocation(java.lang.String date, java.lang.String position, int precision, int altitude, java.lang.String userId) {
		super();
		this.date = date;
		this.position = position;
		this.precision = precision;
		this.altitude = altitude;
		this.userId = userId;
	}

	public int get_id() {
		return _id;
	}
	@JsonProperty
	public void set_id(int id) {
		this._id = id;
	}

	public int getId() {
		return _id;
	}
	@JsonProperty
	public void setId(int id) {
		this._id = id;
	}

	public MobilePrivacyProfilerDBHelper getContextDB(){
		return _contextDB;
	}
	@JsonIgnore
	public void setContextDB(MobilePrivacyProfilerDBHelper contextDB){
		this._contextDB = contextDB;
	}

	public java.lang.String getDate() {
		return this.date;
	}
	@JsonProperty
	public void setDate(java.lang.String date) {
		this.date = date;
	}
	public java.lang.String getPosition() {
		return this.position;
	}
	@JsonProperty
	public void setPosition(java.lang.String position) {
		this.position = position;
	}
	public int getPrecision() {
		return this.precision;
	}
	@JsonProperty
	public void setPrecision(int precision) {
		this.precision = precision;
	}
	public int getAltitude() {
		return this.altitude;
	}
	@JsonProperty
	public void setAltitude(int altitude) {
		this.altitude = altitude;
	}
	public java.lang.String getUserId() {
		return this.userId;
	}
	@JsonProperty
	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}




	public String toXML(String indent, MobilePrivacyProfilerDBHelper contextDB){
		StringBuilder sb = new StringBuilder();
		sb.append(indent+"<");
    	sb.append(XML_GEOLOCATION);
		sb.append(" "+XML_ATT_ID+"=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_DATE);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.date));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_POSITION);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.position));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_PRECISION);
    	sb.append("=\"");
		sb.append(this.precision);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_ALTITUDE);
    	sb.append("=\"");
		sb.append(this.altitude);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_USERID);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.userId));
    	sb.append("\" ");
    	sb.append(">");


		// TODO deal with other case

		sb.append("</"+XML_GEOLOCATION+">");
		return sb.toString();
	}
}
