/*  */
package fr.inria.diverse.mobileprivacyprofilerserver.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collection;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

// Start of user code additional import for MobilePrivacyProfilerDB_metadata
// End of user code

/** 
  * données complémentaires sur la base de donnée 
  */ 
@DatabaseTable(tableName = "mobilePrivacyProfilerDB_metadata")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, 
                  property  = "_id",
				  scope = MobilePrivacyProfilerDB_metadata.class)
public class MobilePrivacyProfilerDB_metadata implements DbClass{

	public static Log log = LogFactory.getLog(MobilePrivacyProfilerDB_metadata.class);

	public static final String XML_MOBILEPRIVACYPROFILERDB_METADATA = "MOBILEPRIVACYPROFILERDB_METADATA";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_CLIENT_ID = "client_id";
	public static final String XML_ATT_LASTTRANSMISSIONDATE = "lastTransmissionDate";
	public static final String XML_ATT_LASTSCANINSTALLEDAPPLICATIONS = "lastScanInstalledApplications";
	public static final String XML_ATT_LASTSCANAPPUSAGE = "lastScanAppUsage";
	public static final String XML_ATT_LASTSMSSCAN = "lastSmsScan";
	public static final String XML_ATT_LASTCALLSCAN = "lastCallScan";
	public static final String XML_ATT_USERID = "userId";
	public static final String XML_ATT_LASTCONTACTSCAN = "lastContactScan";
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	@JsonIgnore
	protected MobilePrivacyProfilerDBHelper _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */


	@DatabaseField
	protected java.util.Date lastTransmissionDate;

	@DatabaseField
	protected java.util.Date lastScanInstalledApplications;

	@DatabaseField
	protected java.util.Date lastScanAppUsage;

	@DatabaseField
	protected java.util.Date lastSmsScan;

	@DatabaseField
	protected java.util.Date lastCallScan;

	@DatabaseField
	protected java.lang.String userId;

	@DatabaseField
	protected java.util.Date lastContactScan;
	

	// Start of user code MobilePrivacyProfilerDB_metadata additional user properties
	// End of user code
	
	public MobilePrivacyProfilerDB_metadata() {} // needed by ormlite
	public MobilePrivacyProfilerDB_metadata(java.util.Date lastTransmissionDate, java.util.Date lastScanInstalledApplications, java.util.Date lastScanAppUsage, java.util.Date lastSmsScan, java.util.Date lastCallScan, java.lang.String userId, java.util.Date lastContactScan) {
		super();
		this.lastTransmissionDate = lastTransmissionDate;
		this.lastScanInstalledApplications = lastScanInstalledApplications;
		this.lastScanAppUsage = lastScanAppUsage;
		this.lastSmsScan = lastSmsScan;
		this.lastCallScan = lastCallScan;
		this.userId = userId;
		this.lastContactScan = lastContactScan;
	}

	/**
	 * raw_id from client converted as part of a primary key in combination of user UUID
	 */
	@DatabaseField
	protected int client_id;

	public int get_id() {
		return client_id;
	}
	@JsonProperty
	public void set_id(int id) {
		this.client_id = id;
	}

	public int getId() {
		return _id;
	}
	@JsonProperty
	public void setId(int id) {
		this._id = id;
	}

	public MobilePrivacyProfilerDBHelper getContextDB(){
		return _contextDB;
	}
	@JsonIgnore
	public void setContextDB(MobilePrivacyProfilerDBHelper contextDB){
		this._contextDB = contextDB;
	}

	public java.util.Date getLastTransmissionDate() {
		return this.lastTransmissionDate;
	}
	@JsonProperty
	public void setLastTransmissionDate(java.util.Date lastTransmissionDate) {
		this.lastTransmissionDate = lastTransmissionDate;
	}
	public java.util.Date getLastScanInstalledApplications() {
		return this.lastScanInstalledApplications;
	}
	@JsonProperty
	public void setLastScanInstalledApplications(java.util.Date lastScanInstalledApplications) {
		this.lastScanInstalledApplications = lastScanInstalledApplications;
	}
	public java.util.Date getLastScanAppUsage() {
		return this.lastScanAppUsage;
	}
	@JsonProperty
	public void setLastScanAppUsage(java.util.Date lastScanAppUsage) {
		this.lastScanAppUsage = lastScanAppUsage;
	}
	public java.util.Date getLastSmsScan() {
		return this.lastSmsScan;
	}
	@JsonProperty
	public void setLastSmsScan(java.util.Date lastSmsScan) {
		this.lastSmsScan = lastSmsScan;
	}
	public java.util.Date getLastCallScan() {
		return this.lastCallScan;
	}
	@JsonProperty
	public void setLastCallScan(java.util.Date lastCallScan) {
		this.lastCallScan = lastCallScan;
	}
	public java.lang.String getUserId() {
		return this.userId;
	}
	@JsonProperty
	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}
	public java.util.Date getLastContactScan() {
		return this.lastContactScan;
	}
	@JsonProperty
	public void setLastContactScan(java.util.Date lastContactScan) {
		this.lastContactScan = lastContactScan;
	}




	public String toXML(String indent, MobilePrivacyProfilerDBHelper contextDB){
		StringBuilder sb = new StringBuilder();
		sb.append(indent+"<");
    	sb.append(XML_MOBILEPRIVACYPROFILERDB_METADATA);
		sb.append(" "+XML_ATT_ID+"=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
		sb.append(XML_ATT_CLIENT_ID);
		sb.append("=\"");
		sb.append(this.client_id);
		sb.append("\" ");
		sb.append(" ");
		sb.append(XML_ATT_LASTTRANSMISSIONDATE);
    	sb.append("=\"");
		sb.append(this.lastTransmissionDate);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_LASTSCANINSTALLEDAPPLICATIONS);
    	sb.append("=\"");
		sb.append(this.lastScanInstalledApplications);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_LASTSCANAPPUSAGE);
    	sb.append("=\"");
		sb.append(this.lastScanAppUsage);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_LASTSMSSCAN);
    	sb.append("=\"");
		sb.append(this.lastSmsScan);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_LASTCALLSCAN);
    	sb.append("=\"");
		sb.append(this.lastCallScan);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_USERID);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.userId));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_LASTCONTACTSCAN);
    	sb.append("=\"");
		sb.append(this.lastContactScan);
    	sb.append("\" ");
    	sb.append(">");


		// TODO deal with other case

		sb.append("</"+XML_MOBILEPRIVACYPROFILERDB_METADATA+">");
		return sb.toString();
	}
}
